name: Bump version
on:
  push:
    branches:
    - "main"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      run: |

curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mansi039/testing/labels -d '{"name":"bug","description":"Something isn'\''t working","color":"f29513"}'
