name: Create Tag on PR Merge
on:
  push
      
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PROJECT_REPO: ${{ github.repository }}



jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag
        

        run: |
          curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" "https://api.github.com/repos/mansi039/testing/git/refs" -d '{"ref": "refs/tags/$NEW_TAG","sha": "${{ github.sha }}"}'
          
          
          
