name: Create TAGG

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2



        env:

          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          LATEST_TAG = $(git describe --abbrev=0 --tags)
          NEW_TAG = $(LATEST_TAG+1)
          curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" "https://api.github.com/repos/mansi039/$PROJECT_REPO/git/refs" -d '{"ref": "refs/tags/$NEW_TAG","sha": "${{ github.sha }}"}'
          

