name: Create Incremental Tag

on:
  pull_request:
    types:
      - closed

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "::set-output name=latest_tag::$LATEST_TAG"

      - name: Determine New Tag
        id: determine_tag
        run: |
          LATEST_TAG=${{ steps.get_latest_tag.outputs.latest_tag }}
          TAG_NUMBER=$(echo $LATEST_TAG | grep -oP '\d+')
          NEW_TAG="v$((TAG_NUMBER + 1))"
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Create Tag
        id: create_tag
        run: |
          NEW_TAG=${{ steps.determine_tag.outputs.new_tag }}
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "::set-output name=tag_name::$NEW_TAG"
          