name: Create Tag on PR Merge
on:
  pull_request:
    types:
      - closed
      
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PROJECT_REPO: ${{ github.repository }}

  TOKEN: ${{ secrets.TOKEN }}

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag
        if: github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          LATEST_TAG = $(git describe --abbrev=0 --tags)
          NEW_TAG = $(LATEST_TAG+1)
          curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" "https://api.github.com/repos/mansi039/$PROJECT_REPO/git/refs" -d '{"ref": "refs/tags/$NEW_TAG","sha": "${{ github.sha }}"}'
          
          
          
