name: GMAIL-TEST
on:
  push
  
  

jobs:          
  GMAIL-TESTING:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        fetch-depth: 2
  

    - name: Send email, you star
      uses: dawidd6/action-send-mail@v1.3.0
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: mansii0903
          password: JUHISATTU9766@
          subject: Your a star
          body: successful job run
          to: mdmansidixit@gmail.com
          from: mansii0903@gmail.com
