name: Create Labels
on:
 push

env:
  
  REPO: ${{ github.repository }}
  GH_TOKEN_PATH: ${{ secrets.GH_TOKEN_PATH }}
  USERNAME: ${{ github.actor }}

jobs:
  creating-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        fetch-depth: 2   
    - name: creating label
      run: |
        
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN_PATH" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mansi039/testing/labels -d '{"name":"timetable","description":"Something isn'\''t working","color":"f29513"}'
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN_PATH" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mansi039/testing/labels -d '{"name":"protected","description":"complete it","color":"f29513"}'
