name: Create Labels
on:
 push

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  REPO: ${{ github.repository }}
  GH_TOKEN_PATH: ${{ secrets.GH_TOKEN_PATH }}
  USERNAME: ${{ github.actor }}

jobs:
  creating-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        fetch-depth: 2   
    - name: creating label
      run: |
        curl -f -X POST https://api.github.com/repos/mansi039/testing/labels -H "Authorization: token $GH_TOKEN_PATH" -d '{"name":": feat","color":"1d76db"}'
        curl -f -X POST https://api.github.com/repos/mansi039/testing/labels -H "Authorization: token $GH_TOKEN_PATH" -d '{"name":": fix","color":"e99695"}'
