name: Create Labels
on:
 push

env:
  
  REPO: ${{ github.repository }}
  GH_TOKEN_PATH: ${{ secrets.GH_TOKEN_PATH }}
  USERNAME: ${{ github.actor }}

jobs:
  creating-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        fetch-depth: 2   
    - name: creating label
      run: |
        curl -f -X POST https://api.github.com/repos/mansi039/testing/labels -H "Authorization: token $GH_TOKEN_PATH" -d '{"name":"feat","description":this is for one","color":"1d76db"}'
        curl -f -X POST https://api.github.com/repos/mansi039/testing/labels -H "Authorization: token $GH_TOKEN_PATH" -d '{"name":"fix","description":this is for two","color":"e99695"}'
