name: Create Labels
on:
  pull_request:
    branches: 
    - 'development'
    - 'release'
    - 'main'
    types:
    - closed

env:
  
  REPO: ${{ github.repository }}
  GH_TOKEN_PATH: ${{ secrets.GH_TOKEN_PATH }}
  USERNAME: ${{ github.actor }}

jobs:  
  Deploy-Jobs:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) &&
      ((contains(github.head_ref, 'user') && github.base_ref == 'development') ||
      (github.head_ref == 'development' && github.base_ref == 'release') ||
      (github.head_ref == 'release' && github.base_ref == 'main') ||
      (contains(github.head_ref, 'hotfix') && github.base_ref == 'release') ||
      (contains(github.head_ref, 'hotfix') && github.base_ref == 'main'))
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout Code
      uses: actions/checkout@main
      with:
        fetch-depth: 2
    - name: creating label-1
      run: |
        
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN_PATH" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mansi039/testing/labels -d '{"name":"akshay","description":"thanks isn'\''t working","color":"f29513"}'
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN_PATH" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mansi039/testing/labels -d '{"name":"singh","description":"neha it","color":"f29513"}'

    - name: creating label-2
      if: 
         (github.event_name == 'pull_request' &&
         github.event.pull_request.merged == true) &&
         (github.head_ref == 'hotfix' && github.base_ref == 'main')
         
      run: |
       echo "running this step as base branch is hotfix"

        
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN_PATH" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mansi039/testing/labels -d '{"name":"aayushi","description":"monkey isn'\''t working","color":"f29513"}'
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN_PATH" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mansi039/testing/labels -d '{"name":"apoorva","description":"donkey it","color":"f29513"}'


        
