name: Add Labels

on:
  pull_request:
    types: opened

jobs:
  Add_Labels:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == false) &&
      ((contains(github.head_ref, 'feature') && github.base_ref == 'development') ||
      (github.head_ref == 'development' && github.base_ref == 'release') ||
      (github.head_ref == 'release' && github.base_ref == 'master') ||
      (contains(github.head_ref, 'hotfix') && github.base_ref == 'release') ||
      (contains(github.head_ref, 'hotfix') && github.base_ref == 'master'))
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: |
            documentation
            changelog
