name: MAIL-TESTING
on:
  push
  

jobs:          
  SEND-NOTIFICATION:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        fetch-depth: 2
  
    - name: Send some mail
      uses: wadeww/send-email-action@master
      with:
        server_address: smtp.gmail.com
        port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Workflow finished
        body: Job completed
        to: mdmansidixit@gmail.com
        from: mdmansidixit@gmail.com
      
