name: MAIL-TESTING
on:
  push
  

jobs:          
  SEND-NOTIFICATION:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        fetch-depth: 2
  
    - name: Install msmtp
      run: sudo apt-get -y install msmtp

    - name: Debug SMTP Configuration
      run: |
       echo "SMTP_SERVER: ${{secrets.SMTP_SERVER}}"
       echo "SMTP_PORT: ${{secrets.SMTP_PORT}}"
       echo "SMTP_USERNAME: ${{secrets.SMTP_USERNAME}}"
       echo "SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}"

    - name: Send Email Notification
      if: success()
      run: |
        echo "Subject: Deployment Successful" > email.txt
        echo "To: mdmansidixit@gmail.com" >> email.txt
        echo "From: mansii0903@gmail.com" >> email.txt
        echo "Content-Type: text/plain; charset=utf-8" >> email.txt
        echo "" >> email.txt
        echo "The deployment was successful." >> email.txt

        msmtp --from=mansii0903@gmail.com \
          --host=${{secrets.SMTP_SERVER}} \
          --port=${{secrets.SMTP_PORT}} \
          --user=${{secrets.SMTP_USERNAME}} \
          --password=${{secrets.SMTP_PASSWORD}} \
          mdmansidixit@gmail.com < email.txt










