name: MAIL-NOTIFICATION
on:
  push
jobs:
    Mail-Sent:
     runs-on: ubuntu-latest
     steps:
     - name: Send some mail
       uses: wadeww/send-email-action@master
       with:
         server_address: smtp.gmail.com
         port: 465
         username: ${{secrets.MAIL_USERNAME}}
         password: ${{secrets.MAIL_PASSWORD}}
         subject: Workflow finished
         body: Job completed ${{job.status}}
         to: mdmansidixit@gmail.com.com
         from: Me


