name: Sync Folders

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sync Folders
        run: |
          rsync -av  ./ $GITHUB_WORKSPACE/

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Sync folders"
          git push
