name: Run-DB-Job-with-JobID

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        options:
          - prod
          - qa
          - dev
          - expl
          
      jobID:
        description: 'ENTER JOB ID'
        required: true
        default: '0'
      tasksToRerun:
        description: 'List of tasks to rerun'
        required: true
      notebookParams:
        description: 'Notebook parameters for the tasks to rerun'
        required: true
      runID:
        description: 'Run ID of existing run'
        required: true
      latestRepairID:
        description: 'Latest repair ID'
        required: true

env:
  RP: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
